
version: 2

models:
  - name: stg_Admission_data
    description: "A starter dbt model"
    columns:
      - name: Name_of_University
        description: "The primary key for this table"
        

  
